// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Mudra(props) {
  var tmp;
  switch (props.mudra) {
    case /* Rock */0 :
        tmp = React.createElement("img", {
              alt: "picture of rock hand",
              src: "/images/pon.png"
            });
        break;
    case /* Paper */1 :
        tmp = React.createElement("img", {
              alt: "picture of paper hand",
              src: "/images/ken.png"
            });
        break;
    case /* Scissors */2 :
        tmp = React.createElement("img", {
              alt: "picture of scissors hand",
              src: "/images/jan.png"
            });
        break;
    
  }
  return React.createElement("div", {
              className: "hand " + (
                props.hand ? "right-hand" : "left-hand"
              ) + ""
            }, tmp);
}

var make = Mudra;

export {
  make ,
}
/* react Not a pure module */
