// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mudra from "./components/mudra/Mudra.bs.js";
import * as React from "react";

import './styles/App.css';
;

function App(props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Jan! Ken! Pon!"), React.createElement(Mudra.make, {
                  hand: /* LeftHand */0,
                  mudra: /* Scissors */2
                }), React.createElement(Mudra.make, {
                  hand: /* RightHand */1,
                  mudra: /* Paper */1
                }));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
