// Generated by ReScript, PLEASE EDIT WITH CARE


function determineWinner(move1, move2) {
  var player2Choice = move2.mudra;
  switch (move1.mudra) {
    case /* Rock */0 :
        if (player2Choice !== 1) {
          return /* Draw */0;
        } else {
          return /* WinnerWas */{
                  _0: move1.player
                };
        }
    case /* Paper */1 :
        if (player2Choice !== 0) {
          return /* Draw */0;
        } else {
          return /* WinnerWas */{
                  _0: move2.player
                };
        }
    case /* Scissors */2 :
        return /* Draw */0;
    
  }
}

function determineScore(player, matchHistory) {
  return 0;
}

var player1 = {
  TAG: /* Player1 */0,
  _0: "aten6"
};

var player2 = {
  TAG: /* Player2 */1,
  _0: "Wakamomo"
};

var matchHistory = {
  hd: /* Draw */0,
  tl: /* [] */0
};

var jonkenpon = determineWinner;

export {
  player1 ,
  player2 ,
  matchHistory ,
  jonkenpon ,
  determineScore ,
}
/* No side effect */
