// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as Client from "react-dom/client";

import './styles/Index.css';
;

var node = document.getElementById("root");

if (!(node == null)) {
  var root = Client.createRoot(node);
  root.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
